=== jbouduin/holiday/util/configuration-validation/schema/hierarchy.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "http://example.com/schemas/hierarchy",
  "title": "Hierarchy",
  "description": "A hierarchy",
  "type": "object",
  "required": ["hierarchy", "description", "holidays"],
  "properties": {
    "hierarchy": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "holidays": {
      "type":"array",
      "items": {
        "allOf": [
          {
            "$ref": "http://example.com/schemas/holiday#/definitions/holiday"
          }
        ]
      }
    },
    "subConfigurations": {
      "type": "array",
      "items": {
        "$ref": "http://example.com/schemas/hierarchy"
      }
    }
  },
  "additionalProperties": false
}

=== jbouduin/holiday/packages/holidays-lib/src/assets/configurations/de.json
{
  "hierarchy": "de",
  "description": "Germany",
  "holidays": [
    {
      "holidayType": "CHRISTIAN",
      "key": "EASTER"
    },
    {
      "holidayType": "CHRISTIAN",
      "key": "GOOD_FRIDAY"
    },
    {
      "holidayType": "CHRISTIAN",
      "key": "EASTER_MONDAY"
    },
    {
      "holidayType": "CHRISTIAN",
      "key": "ASCENSION_DAY"
    },
    {
      "holidayType": "CHRISTIAN",
      "key": "WHIT_SUNDAY"
    },
    {
      "holidayType": "CHRISTIAN",
      "key": "WHIT_MONDAY"
    },
    {
      "holidayType": "FIXED_DATE",
      "key": "NEW_YEAR",
      "month": "JANUARY",
      "day": 1
    },
    {
      "holidayType": "FIXED_DATE",
      "key": "LABOUR_DAY",
      "month": "MAY",
      "day": 1
    },
    {
      "holidayType": "FIXED_DATE",
      "key": "UNIFICATION",
      "month": "JUNE",
      "day": 17,
      "validFrom": 1954,
      "validTo": 1990
    },
    {
      "holidayType": "FIXED_DATE",
      "key": "UNIFICATION",
      "month": "OCTOBER",
      "day": 3,
      "validFrom": 1990
    },
    {
      "holidayType": "FIXED_DATE",
      "key": "CHRISTMAS",
      "month": "DECEMBER",
      "day": 25
    },
    {
      "holidayType": "FIXED_DATE",
      "key": "STEPHENS",
      "month": "DECEMBER",
      "day": 26
    }
  ],
  "subConfigurations": [
    {
      "hierarchy": "bb",
      "description": "Brandenburg",
      "holidays": [
        {
          "holidayType": "FIXED_DATE",
          "key": "REFORMATION_DAY",
          "month": "OCTOBER",
          "day": 31
        }
      ]
    },
    {
      "hierarchy": "bw",
      "description": "Baden-Württenberg",
      "holidays": [
        {
          "holidayType": "CHRISTIAN",
          "key": "CORPUS_CHRISTI"
        },
        {
          "holidayType": "FIXED_DATE",
          "key": "EPIPHANY",
          "month": "JANUARY",
          "day": 6
        },
        {
          "holidayType": "FIXED_DATE",
          "key": "ALL_SAINTS",
          "month": "NOVEMBER",
          "day": 1
        }
      ]
    },
    {
      "hierarchy": "by",
      "description": "Bayern",
      "holidays": [
        {
          "holidayType": "CHRISTIAN",
          "key": "CORPUS_CHRISTI"
        },
        {
          "holidayType": "FIXED_DATE",
          "key": "EPIPHANY",
          "month": "JANUARY",
          "day": 6
        },
        {
          "holidayType": "FIXED_DATE",
          "key": "ALL_SAINTS",
          "month": "NOVEMBER",
          "day": 1
        }
      ],
      "subConfigurations": [
        {
          "hierarchy": "mu",
          "description": "Munich",
          "holidays": [
            {
              "holidayType": "FIXED_DATE",
              "key": "ASSUMPTION_DAY",
              "month": "AUGUST",
              "day": 15
            }
          ]
        },
        {
          "hierarchy": "ag",
          "description": "Augsburg",
          "holidays": [
            {
              "holidayType": "FIXED_DATE",
              "key": "PEACE",
              "month": "AUGUST",
              "day": 8
            },
            {
              "holidayType": "FIXED_DATE",
              "key": "ASSUMPTION_DAY",
              "month": "AUGUST",
              "day": 15
            }
          ]
        },
        {
          "hierarchy": "wu",
          "description": "Würzburg",
          "holidays": [
            {
              "holidayType": "FIXED_DATE",
              "key": "ASSUMPTION_DAY",
              "month": "AUGUST",
              "day": 15
            }
          ]
        },
        {
          "hierarchy": "re",
          "description": "Regensburg",
          "holidays": [
            {
              "holidayType": "FIXED_DATE",
              "key": "ASSUMPTION_DAY",
              "month": "AUGUST",
              "day": 15
            }
          ]
        },
        {
          "hierarchy": "in",
          "description": "Ingolstadt",
          "holidays": [
            {
              "holidayType": "FIXED_DATE",
              "key": "ASSUMPTION_DAY",
              "month": "AUGUST",
              "day": 15
            }
          ]
        }
      ]
    },
    {
      "hierarchy": "he",
      "description": "Hessen",
      "holidays": [
        {
          "holidayType": "CHRISTIAN",
          "key": "CORPUS_CHRISTI"
        }
      ]
    },
    {
      "hierarchy": "mv",
      "description": "Mecklenburg-Vorpommern",
      "holidays": [
        {
          "holidayType": "FIXED_DATE",
          "key": "REFORMATION_DAY",
          "month": "OCTOBER",
          "day": 31
        }
      ]
    },
    {
      "hierarchy": "nw",
      "description": "Nordrhein-Westfalen",
      "holidays": [
        {
          "holidayType": "CHRISTIAN",
          "key": "CORPUS_CHRISTI"
        },
        {
          "holidayType": "FIXED_DATE",
          "key": "ALL_SAINTS",
          "month": "NOVEMBER",
          "day": 1
        }
      ]
    },
    {
      "hierarchy": "rp",
      "description": "Rheinland-Pfalz",
      "holidays": [
        {
          "holidayType": "CHRISTIAN",
          "key": "CORPUS_CHRISTI"
        },
        {
          "holidayType": "FIXED_DATE",
          "key": "ALL_SAINTS",
          "month": "NOVEMBER",
          "day": 1
        }
      ]
    },
    {
      "hierarchy": "sl",
      "description": "Saarland",
      "holidays": [
        {
          "holidayType": "CHRISTIAN",
          "key": "CORPUS_CHRISTI"
        },
        {
          "holidayType": "FIXED_DATE",
          "key": "ALL_SAINTS",
          "month": "NOVEMBER",
          "day": 1
        },
        {
          "holidayType": "FIXED_DATE",
          "key": "ASSUMPTION_DAY",
          "month": "AUGUST",
          "day": 15
        }
      ]
    },
    {
      "hierarchy": "sn",
      "description": "Sachsen",
      "holidays": [
        {
          "holidayType": "FIXED_DATE",
          "key": "REFORMATION_DAY",
          "month": "OCTOBER",
          "day": 31
        },
        {
          "holidayType": "RELATIVE_TO_DATE",
          "key": "REPENTANCE_PRAYER",
          "relation": {
            "weekday": "WEDNESDAY",
            "when": "BEFORE"
          },
          "fix": {
            "month": "NOVEMBER",
            "day": 23
          }
        }
      ]
    },
    {
      "hierarchy": "st",
      "description": "Sachsen-Anhalt",
      "holidays": [
        {
          "holidayType": "FIXED_DATE",
          "key": "REFORMATION_DAY",
          "month": "OCTOBER",
          "day": 31
        },
        {
          "holidayType": "FIXED_DATE",
          "key": "EPIPHANY",
          "month": "JANUARY",
          "day": 6
        }
      ]
    },
    {
      "hierarchy": "th",
      "description": "Thüringen",
      "holidays": [
        {
          "holidayType": "FIXED_DATE",
          "key": "REFORMATION_DAY",
          "month": "OCTOBER",
          "day": 31
        }
      ]
    }
  ]
}

=== jbouduin/holiday/packages/holidays-lib/__tests__/hierarchy-calculator/data/valid/configurations/l1.json
{
  "hierarchy": "l1",
  "description": "aa",
  "holidays": [
    { "holidayType": "FIXED_DATE", "key": "l1", "month": "JANUARY", "day": 1 }
  ],
  "subConfigurations": [
    {
      "hierarchy": "l1.1",
      "description": "l1.1",
      "holidays": [
        { "holidayType": "FIXED_DATE", "key": "l1.1", "month": "JANUARY", "day": 1 }
      ]
    },
    {
      "hierarchy": "l1.2",
      "description": "l1.2",
      "holidays": [
        { "holidayType": "FIXED_DATE", "key": "l1.2", "month": "JANUARY", "day": 1 }
      ],
      "subConfigurations": [
        {
          "hierarchy": "l1.2.1",
          "description": "l1.2.1",
          "holidays": [
            { "holidayType": "FIXED_DATE", "key": "l1.2.1", "month": "JANUARY", "day": 1 }
          ]
        },
        {
          "hierarchy": "l1.2.2",
          "description": "l1.2.2",
          "holidays": [
            { "holidayType": "FIXED_DATE", "key": "l1.2.2", "month": "JANUARY", "day": 1 }
          ]
        }
      ]
    },
    {
      "hierarchy": "l1.3",
      "description": "l1.3",
      "holidays": [
        { "holidayType": "FIXED_DATE", "key": "l1.3", "month": "JANUARY", "day": 1 }
      ],
      "subConfigurations": [
        {
          "hierarchy": "l1.3.1",
          "description": "l1.3.1",
          "holidays": [
            { "holidayType": "FIXED_DATE", "key": "l1.3.1", "month": "JANUARY", "day": 1 }
          ]
        },
        {
          "hierarchy": "l1.3.2",
          "description": "l1.3.2",
          "holidays": [
            { "holidayType": "FIXED_DATE", "key": "l1.3.2", "month": "JANUARY", "day": 1 }
          ],
          "subConfigurations": [
            {
              "hierarchy": "l1.3",
              "description": "l1.3 bis",
              "holidays": [
                { "holidayType": "FIXED_DATE", "key": "l1.3 bis", "month": "JANUARY", "day": 1 }
              ]
            }
          ]
        }
      ]
    }
  ]
}
